version: '3.8'
services:
  frontend:
    build:
      target: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`samyhama.fr`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
