version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
